version: "3.8"
services:
  app:
    build:
      context: .
      target: dev
    command: npm run dev
    image: sports-center:devlopment
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    env_file:
      - .env
