version: "3.8"
services:
  app:
    build:
      context: .
      target: production
    command: npm run dev
    image: sport-center:production
    volumes:
      - .:/app
    ports:
      - 5100:5000
    env_file:
      - .env
